language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - curl https://raw.githubusercontent.com/CloudDefenseAI/cd/master/latest/cd-latest-linux-x64.tar.gz > /tmp/cd-latest-linux-x64.tar.gz && tar -C /tmp -xzf /tmp/cd-latest-linux-x64.tar.gz && chmod +x /tmp/cdefense
  - export SCAN_URL=https://cd-scanner.herokuapp.com
  - /tmp/cdefense scan --lang=python --project-name=vulnerable-python-travis-ci --api-key=75a81a24-adfc-4bfd-8b32-7562169a9759 --path=requirements.txt --verbose
