# This is a basic workflow to help you get started with Actions

name: Python SAST CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: cdefense/sast-scan:latest
      options: -e "WORKSPACE=/__w/vulnerable-python/vulnerable-python"
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Cloud Defense SAST Scan
      env:
        SAST_SCAN_URL: https://console-qa.clouddefenseai.com/scan/sast
      run: python3 /usr/local/src/scan --src /__w/vulnerable-python/vulnerable-python --type python --app_name vulnerable-python --api-key ${{ secrets.CD_API_KEY }}
