# This workflow will install Python dependencies, run SCA scan with a single version of Python

name: Python SCA CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
jobs:
  sca-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '2'
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        #pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@master
    - name: Cloud Defense SCA Scan
      env:
        SCAN_URL: https://cd-scanner.herokuapp.com
        CD_API_KEY: ${{ secrets.CD_API_KEY }}
        GIT_SHA: ${GITHUB_SHA}
      run: |
        echo GITHUB_SHA: $GITHUB_SHA
        echo GIT_SHA: $GIT_SHA
        curl https://raw.githubusercontent.com/CloudDefenseAI/cd/test/latest/cd-latest-linux-x64.tar.gz > /tmp/cd-latest-linux-x64.tar.gz && tar -C /tmp -xzf /tmp/cd-latest-linux-x64.tar.gz && chmod +x /tmp/cdefense
        /tmp/cdefense scan -q --lang=python --project-name=vulnerable-python
