# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python SCA CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        #pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Cloud Defense Scan
      env:
        #SCA_SCAN_URL: https://cd-scanner.herokuapp.com/processAndSave
        SCAN_URL: https://cd-scanner.herokuapp.com
        CD_API_KEY: ${{ secrets.CD_API_KEY }}
      run: |
        curl https://raw.githubusercontent.com/CloudDefenseAI/cd/master/latest/cd-latest-linux-x64.tar.gz > /tmp/cd-latest-linux-x64.tar.gz && tar -C /tmp -xzf /tmp/cd-latest-linux-x64.tar.gz && chmod +x /tmp/cdefense
        /tmp/cdefense scan --verbose -q --lang=python --project-name=vulnerable-python --path=${PWD}
